In [1]:
import json
import numpy as np
from sage.all import Graph, Matroid, SymmetricGroup, ZZ, graphs

n = 3

edgelist = graphs.CompleteGraph(n).edges(labels=False)
matroid = Matroid(graph=edgelist, groundset=edgelist)

group = SymmetricGroup(range(n))
conjugacy_class_reps = group.conjugacy_classes_representatives()
partitions = reversed([x.cycle_type() for x in conjugacy_class_reps])

def representations(n):
        representations = []
        for partition in partitions:
            character_values = SymmetricGroupRepresentation(partition).to_character().values()
            int_values = [int(value) for value in character_values]
            representations.append(int_values)
            
        return representations

def decomposition(characters_list, n):
    trace_matrix = np.matrix(representations(n), dtype=float)
    decomposition = []
    A = np.array(trace_matrix.transpose())
    print(A)
    for v in characters_list:
        rhs_array = np.array(v, dtype=float)
        solution = np.linalg.solve(A, rhs_array)
        rounded_solution = np.round(solution).astype(int)
        decomposition.append(rounded_solution.tolist())

    return decomposition

def action_on_groundset(g, x):
    return tuple(sorted(g(y) for y in x))

def action_on_subset(g, S):
    return frozenset([action_on_groundset(g, x) for x in S])

OSG = matroid.orlik_solomon_algebra(ZZ)
equivOSG = []

for i in range(matroid.rank() + 1):
    basis = OSG.basis(i)
    print(basis)
    trace_matrix = []
    for g in conjugacy_class_reps:
        trace = 0
        for key in basis.keys():
            action_image = action_on_subset(g, key)
            #print(OSG.subset_image(action_image), OSG.subset_image(key))
            if OSG.subset_image(action_image) == OSG.subset_image(key):
                trace += 1
        trace_matrix.append(trace)
    equivOSG.append(trace_matrix)

print(
print([len(OSG.basis(i)) for i in range(matroid.rank() + 1)])
print(equivOSG)
print(decomposition(equivOSG, n))
print(matroid.no_broken_circuits_sets())


Finite family {frozenset(): OS{}} [frozenset()]
Finite family {frozenset({(1, 2)}): OS{(1, 2)}, frozenset({(0, 2)}): OS{(0, 2)}, frozenset({(0, 1)}): OS{(0, 1)}} [frozenset({(1, 2)}), frozenset({(0, 2)}), frozenset({(0, 1)})]
Finite family {frozenset({(0, 1), (1, 2)}): OS{(0, 1), (1, 2)}, frozenset({(0, 1), (0, 2)}): OS{(0, 1), (0, 2)}} [frozenset({(0, 1), (1, 2)}), frozenset({(0, 1), (0, 2)})]
[1, 3, 2]
[[1, 1, 1], [3, 1, 0], [2, 0, 0]]
[[ 1.  2.  1.]
 [ 1.  0. -1.]
 [ 1. -1.  1.]]
[[1, 0, 0], [1, 1, 0], [0, 1, 0]]
[frozenset(), frozenset({(1, 2)}), frozenset({(0, 2)}), frozenset({(0, 1)}), frozenset({(0, 1), (1, 2)}), frozenset({(0, 1), (0, 2)})]
